OSC_CORE = ('localhost', 1420)
OSC_GUI = ('localhost', 1421)
b = 'coreaudio'
TITLE_BROWSER = 'pineal-browser'
OUTPUT_SIZE = (640, 480)
FULLSCREEN = True
setted = ['Gui']
k = 'osc-gui'
TITLE = 'Pineal Loop Project'
MODULES = ['Gui']
TITLE_OVERVIEW = 'pineal-overview'
VISUALS_PATH = '../../visuals'
p = 'Gui'
backends = ('portaudio', 'jack', 'coreaudio')
kw = 'output'
RENDER_SIZE = (640, 480)
arg = '--gui'
BACKEND = 'portaudio'
