// DO NOT EDIT THIS FILE
// generated using scripts/generate.hy and code in src/dsl/

#pragma once
#define PINEAL(_)

namespace dsl{
	#include "dsl/colors.h"
	#include "dsl/primitives.h"
	#include "dsl/osc.h"
	#include "dsl/transformations.h"
	#include "dsl/layers.h"
	#include "dsl/audio.h"

	BOOST_PYTHON_MODULE(core){
		py::class_<pEntity>("pEntity")
		    .def(py::init<py::object>())
		;

		py::class_<pAction>("pAction")
		    .def("__call__", &pAction::__call__)
		;

		py::class_<pValue>("pValue")
		    .def(py::init<float>())
		    .def("__call__", &pValue::__call__0)
		    .def("__call__", &pValue::__call__1)
		    .def("__call__", &pValue::__call__2)
		;

		py::def("background", &colors::background);
		py::def("color", &colors::color);
		py::def("fill", &colors::fill);
		py::def("no_fill", &colors::no_fill);
		py::def("line_width", &colors::line_width);

		py::def("draw", &primitives::draw);
		py::def("group", &primitives::group);
		py::def("cube", &primitives::cube);
		py::def("polygon", &primitives::polygon);

		py::def("osc_value", &osc::get_value_with_default);
		py::def("osc_value", &osc::get_value);

		py::def("hide", &transformations::hide);
		py::def("scale", &transformations::scale);
		py::def("translate", &transformations::translate);
		py::def("rotate_x", &transformations::rotate_x);
		py::def("rotate_y", &transformations::rotate_y);
		py::def("rotate_z", &transformations::rotate_z);
		py::def("turn_x", &transformations::turn_x);
		py::def("turn_y", &transformations::turn_y);
		py::def("turn_z", &transformations::turn_z);

		py::def("on_layer_c", &layers::on_layer);
		py::def("layer_entity", &layers::layer_entity);

		py::def("rms", &audio::rms);
		py::def("at_event", &audio::at_event);
		py::def("at_beat", &audio::at_beat);
		py::def("at_onset", &audio::at_onset);}
}