// DO NOT EDIT THIS FILE
// generated using scripts/generate.hy and code in src/dsl/

#pragma once
#define PINEAL(_)

namespace dsl{
	#include "dsl/colors.h"
	#include "dsl/primitives.h"
	#include "dsl/keywords.h"
	#include "dsl/osc.h"
	#include "dsl/transformations.h"
	#include "dsl/layers.h"
	#include "dsl/audio.h"

	BOOST_PYTHON_MODULE(core){
		py::class_<pEntity>("pEntity")
		    .def(py::init<py::object>())
		;

		py::class_<pAction>("pAction")
		    .def("__call__", &pAction::__call__)
		;

		py::class_<pColor>("pColor");

		py::def("background", &colors::background);
		py::def("lerp", &colors::lerp);
		py::def("invert", &colors::invert);
		py::def("rgb_c", &colors::rgb);
		py::def("color", &colors::color);
		py::def("fill", &colors::fill);
		py::def("no_fill", &colors::no_fill);
		py::def("line_width", &colors::line_width);

		py::def("cube", &primitives::cube);
		py::def("polygon", &primitives::polygon);
		py::def("text_c", &primitives::text);

		py::def("draw", &keywords::draw);
		py::def("compose_c", &keywords::compose);
		py::def("branch_c", &keywords::branch);
		py::def("change_c", &keywords::change);
		py::def("group_c", &keywords::group_exposed);

		py::def("get_osc_f_c", &osc::get_osc_f_with_default);
		py::def("get_osc_f_c", &osc::get_osc_f);

		py::def("hide", &transformations::hide);
		py::def("scale_c", &transformations::scale);
		py::def("translate_c", &transformations::translate);
		py::def("rotate_x", &transformations::rotate_x);
		py::def("rotate_y", &transformations::rotate_y);
		py::def("rotate_z", &transformations::rotate_z);

		py::def("on_layer_c", &layers::on_layer);
		py::def("layer_entity", &layers::layer_entity);

		py::def("rms", &audio::rms);
		py::def("at_event", &audio::at_event);
		py::def("at_beat", &audio::at_beat);
		py::def("at_onset", &audio::at_onset);}
}